#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# rbnev
eval "$(rbenv init -)"

# pyenv
eval "$(pyenv init -)"

# go
export GOPATH=$(go env GOPATH)
export PATH=$PATH:$GOPATH/bin

# peco
bindkey '^]' peco-src
function peco-src() {
  local src=$(ghq list --full-path | peco --query "$LBUFFER")
  if [ -n "$src" ]; then
    BUFFER="cd $src"
    zle accept-line
  fi
  zle -R -c
}
zle -N peco-src

# Poetry?
fpath+=~/.zfunc

# nodenv
eval "$(nodenv init -)"
